require 'rubygems'
require 'yaml'
require 'pp'
require 'rdf'
require 'rdf/sesame'
require 'active_support'
require 'jira4r'
require 'find'

require 'utils'
require 'vocabulary'
require 'connection'
require 'comment'
require 'command'
require 'semantic'