require 'rubygems'
require 'yaml'
require 'utils'
require 'pp'
require 'rdf'
require 'rdf/sesame'
require 'active_support'

require 'vocabulary'
require 'connection'
require 'comment'
require 'command'